Day_6/redirects_sample/__init__.py
from flask import Flask
from .redirect_blueprint import redirect_bp


def create_app():
    app = Flask(__name__)
    app.register_blueprint(redirect_bp)
    return app

Day_6/redirects_sample/redirect_blueprint.py
from flask import Blueprint, render_template, request, redirect

redirect_bp = Blueprint('redirect_bp', __name__)


@redirect_bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        return render_template('index.html')
    if request.method == 'POST':
        username = request.form.get("username")
        return render_template('welcome.html', username=username)


@redirect_bp.route('/new', methods=['POST'])
def new():
    if request.method == 'POST':
        return redirect('/')

Day_6/redirects_sample/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        welcome
    </title>
</head>
<body>
    Welcome to our page!!!
    <form action="{{ url_for('redirect_bp.index') }}" method="post">
        <label for="username">First name:</label><br>
        <input type="text" id="username" name="username" value="username">
        <br>
        <input type="submit" value="Submit">
    </form>

</body>
</html>

Day_6/redirects_sample/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        welcome {{ username }}
    </title>
</head>
<body>
    Hello {{ username }} you are logged into the site!!!
</body>
</html>